### ISSUE TITLE
Q: `trySuccess` vs `success`

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#10]
Within `fileCreated` (page 122), why use `trySuccess` instead of `success` (assumed `-Ywarn-value-discard` is off)?

Just before this example, you stated:

>As long as we do not use the trySuccess, tryFailure, and tryComplete methods, and none of the success, failure, and complete methods ever throws an exception, we can use promises and retain determinism in our programs.

Can you elaborate why, e.g., `trySuccess` does not retain determinism?

Deterministic means that, given that no exception is thrown in the program, the result of the program will always be the same, regardless of the execution schedule of the parallel program. 

So why does `trySuccess` violate here? Or, how does `trySuccess` depend on the execution schedule?

**Comment by axel22** [comment]
In this particular example, you need to have some determinism - nondeterminism cannot be avoided. The `FileAlterationListener` represents an external event source, which may trigger zero, one or more events. Since the `Promise`/`Future` can hold at most a single event, only the first (that is, the quickest) invocation of `onFileCreate` can complete the promise object `p`.

If we use `success` to complete the promise, then if the external event source emits to file creation events, the `onFileCreate` will be called twice, and one of the `success` calls will throw an exception.
With our definition of determinism, this is deterministic, but not particularly useful - if we ignore the exception, then the rest of the program that depends on the value in the promise becomes non-deterministic anyway.

If we use `trySuccess`, one of the calls will similarly not succeed, but an exception will not be thrown. In cases like this, where you cannot avoid determinism, it's sometimes better to just use `trySuccess`.

**Comment by normenmueller** [comment]
>In this particular example, you need to have some determinism - nondeterminism cannot be avoided. The FileAlterationListener represents an external event source, which may trigger zero, one or more events. Since the Promise/Future can hold at most a single event, only the first (that is, the quickest) invocation of onFileCreate can complete the promise object p.

Good explanation.

>If we use success to complete the promise, then if the external event source emits two file creation events, the onFileCreate will be called twice, and one of the success calls will throw an exception. With our definition of determinism, this is deterministic, but not particularly useful - if we ignore the exception, then the rest of the program that depends on the value in the promise becomes non-deterministic anyway.

>If we use trySuccess, one of the calls will similarly not succeed, but an exception will not be thrown. In cases like this, where you cannot avoid determinism, it's sometimes better to just use trySuccess.

"where you cannot avoid nondeterminism", nor?

**Comment by axel22** [comment]
Yes, typo - "where you cannot avoid nondeterminism".
