### ISSUE TITLE
Unit test for Concurrent Code

### ISSUE THREAD

**Issue by satybald** [concurrent-programming-in-scala/learning-examples#3]
I almost finished reading the book. Thanks @axel22 for writing and publishing the book. I really enjoy reading it. It was also very informative for me.

One of the questions that I left after reading the book: is it possible to run unit testing suite for concurrent code?

**Comment by satybald** [comment]
One more question regarding testing for concurrent code: is there any method to determine if the concurrent realization is correctly implemented?

In the book was mentioned that it's possible to determine a deadlock with visual vm. Is there any tool or way to think about race conditions?

In terms of Atomic stack example, how can we reason about its methods are properly synchronized?

**Comment by axel22** [comment]
That section of the book describes how to *debug* concurrent code. The trouble with data races, unlike deadlocks, is that you usually see some after-effect of invalid behavior, instead of immediate failure. Backwards reasoning and log traces are often the only way to track data races.

A way to avoid (or reduce) the troubles associated with debugging is to *test* the code extensively. In practice, exhaustive unit tests that simulate different execution scenarios are the way to detect and localize errors early. This is why I recommended using ScalaCheck - it can conveniently create a large number of inputs for the test.

*Reasoning* about the correctness of the program is the third way of ensuring correctness, and it is the least developed one. Automatic verification frameworks for concurrent code are still an active research topic.

The best general advice I can give is:
- keep your concurrency utilities modular, short and self-contained, to reason about them more easily
- do heavy unit testing on self-contained concurrency modules

In the `AtomicStack` example, you should ensure that the items XS the thread T has pushed onto the stack are popped in the opposite order. Items YS that were pushed by another thread S should be ignored, as long as they do not change the order in which items XS are popped.

A ScalaCheck test would be something like the following:

    ...scalacheck for-all statement (see scalacheck docs)... {
      val stack = newStack
      val t = thread {
        for (i <- 0 until 100) stack.push(i)
        val seen = new mutable.ArrayBuffer[Int]
        while (stack.nonEmpty) seen += stack.pop()
        assert(seen.filter(x => x >= 0 && x < 100).reverse == (0 until 100))
      }
      val s = thread {
        for (i <- 1000 until 1100) stack.push(i)
      }
      t.join()
      s.join()
    }

**Comment by satybald** [comment]
Wow, @axel22 thanks for the thoughtful answer with a decent example! I think, I finally got the point with multithreading testing.
