### ISSUE TITLE
Deadlock at page 45: Why `t1` locks `a` and `t2` locks `b`?

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#4]
Why can it happen that thread `t1` locks `a` and `t2` locks `b`?

`b` is sychronized within the `a.sychronized` block and if `t1` has locked `a`, how can it be that `t2` enters the `a.synchronized` block to lock `b`? 

What am I missing here?

    class Account(val name: String, var money: Int)
    
    def send(a: Account, b: Account, n: Int) = a.synchronized {
      b.synchronized {
        a.money -= n
        b.money += n
      }
    }
    
    val a = new Account("Jack", 1000)
    val b = new Account("Jill", 2000)
    val t1 = thread { for (i<- 0 until 100) send(a, b, 1) }
    val t2 = thread { for (i<- 0 until 100) send(b, a, 1) }
    t1.join(); t2.join()
    log(s"a = ${a.money}, b = ${b.money}")

**Comment by axel22** [comment]
Thanks, and glad to hear that you're enjoying the book!

The reason is that the thread t1 calls `send` with the Account `a` from the main program at the first argument, and the Account `b` at the second place, while the thread t2 does the opposite - it calls the Account `b` as the first argument, and `a` as the second. The synchronized statement is called for the two objects `a` and `b` from the main program in the opposite order in the two invocations by the thread `t1` and `t2`.

In retrospect, could have been better to call the accounts in the main program `x` and `y`, to avoid the confusion.

Hope this helps!
