### ISSUE TITLE
Sample solutions

### ISSUE THREAD

**Issue by normenmueller** [concurrent-programming-in-scala/learning-examples#5]
Are there any sample solutions available to ensure one's own?

**Comment by axel22** [comment]
Hi Normen,

There are currently not sample solutions available. This is partly because many of the exercises are open-ended, and have multiple approaches and solutions.

I did, however, add the `exercises` package, which is currently empty. The hope is for people to submit their own solutions, and have them peer-reviewed. In some cases, there might be several solutions to the same exercise.

If you would like to submit some of your sample solutions, I'd be happy to take a look at them, and merge them in.

**Comment by normenmueller** [comment]
Hi Alex,

>There are currently not sample solutions available. This is partly because [...] have multiple approaches and solutions.

Yes, that is surely true but sample solutions are often worthwhile to keep your students going and not frustrated. Just saying.

**Comment by axel22** [comment]
This is true. Since the exercises were added at a later stage during the writing of the book, I had no time so far to add some solutions myself. I hope to add some incrementally in the coming months.

**Comment by Kay000** [comment]
I would be really happy about sample solutions as well. 
So if anybody has some please upload. I will submit them too.

**Comment by axel22** [comment]
I'll try to address this with the bandwidth I currently have (btw, there is already a [PR with some sollutions](https://github.com/concurrent-programming-in-scala/learning-examples/pull/6))
